### ISSUE TITLE
2 comments

### ISSUE THREAD

**Issue by PD1LOI** [satdreamgr/SDGRadio#14]
I have 2 more comments
1: Why is the skin code written so differently than normal
now (% d,% d) prefer 0.0.
2: Why there is no complete package like .ipk
so you can always find the latest version.

**Comment by nautilus7** [comment]
The plugin skin can be adjusted depending on the resolution of the enigma2 skin used, i.e. is scalable.

We don't provide .ipk. You can always find the latest inside the SatDreamGr images, or if you use a different image, you can ask their developers to add the plugin in the feed.
